name: Build WF
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00 every Sunday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6-beta
        with:
          fetch-depth: 0

      - name: Maven Build
        run: mvn install

  Testing:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6-beta
        with:
          fetch-depth: 0

      - name: Run tests on main branch
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:check
