name: Build WF
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: "0 0 * * 0" # Runs at 00:00 every Sunday

env:
  ECR_REPOSITORY: vprofile-appimage

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6-beta
        with:
          fetch-depth: 0

      - name: Maven Build
        run: mvn install

      - name: Upload Build Artifacts (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

      - name: Notify if Build Fails
        if: failure()
        run: echo "Build job failed! Please check the logs."

  Testing:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6-beta
        with:
          fetch-depth: 0

      - name: Run tests on main branch
        if: github.ref == 'refs/heads/main'
        run: mvn test

      - name: Checkstyle
        if: github.ref == 'refs/heads/main'
        run: mvn checkstyle:check

      - name: Run test on other branches
        if: github.ref != 'refs/heads/main'
        run: echo "Tests are skipped on non-main branches."

  Security-Scan:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Code Checkout
        uses: actions/checkout@v6-beta
        with:
          fetch-depth: 0

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          format: json
          exit-code: 0
          vun-type: os,library
          output: trivy-results.json

      - name: Upload Trivy scan result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan-results
          path: trivy-results.json

  BUILD_AND_PUBLISH:
    name: BUILD_AND_PUBLISH
    runs-on: ubuntu-latest
    environment:
      name: production
    needs: [Build, Security-Scan]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6-beta
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRETE_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f Docker-files/app/multistage/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
